import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, relative } from 'node:path';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
const { applyWindowsIcon, updateShortcutIcons } = createRequire(import.meta.url)('../electron/windows-icon.cjs');

test('updates installed and manual shortcuts, including Start menu subfolders, without changing launch properties', async () => {
    const directory = await mkdtemp(join(tmpdir(), 'orbitcord-pins-'));
    const executable = 'C:\\Apps\\OrbitCord\\OrbitCord.exe';
    const appId = 'dev.lowcord.app';
    const icon = 'C:\\Profile\\app-icons\\mint.ico';
    const links = {
        'OrbitCord.lnk': { target: executable.toLowerCase(), appUserModelId: appId, icon: 'old.ico', iconIndex: 0,
            args: '--user-option', cwd: 'C:\\Apps\\OrbitCord', description: 'My pin' },
        'Other install.lnk': { target: 'D:\\OrbitCord.exe', appUserModelId: appId },
        'Other app.lnk': { target: executable, appUserModelId: 'other.app' },
        'Manual pin.lnk': { target: executable, appUserModelId: '', icon: 'old.ico', iconIndex: 0 },
        'Automatic pin.lnk': { target: executable, appUserModelId: 'Microsoft.AutoGenerated.some-hash', icon: 'old.ico', iconIndex: 0 },
        'nested/Start menu.lnk': { target: executable, icon: 'old.ico', iconIndex: 0 },
        'Already current.LNK': { target: executable, appUserModelId: appId, icon, iconIndex: 0 },
        'Broken.lnk': null,
        'readme.txt': null,
    };
    try {
        await mkdir(join(directory, 'nested'));
        for (const name of Object.keys(links)) await writeFile(join(directory, name), '');
        const writes = [];
        const shell = {
            readShortcutLink(path) {
                const name = relative(directory, path).replaceAll('\\', '/');
                if (!links[name]) throw new Error('Unreadable shortcut');
                return links[name];
            },
            writeShortcutLink(path, operation, changes) {
                writes.push({ path, operation, changes });
                Object.assign(links[relative(directory, path).replaceAll('\\', '/')], changes);
                return true;
            },
        };
        await updateShortcutIcons(directory, executable, appId, icon, shell);
        assert.deepEqual(writes.map(write => write.path).sort(), ['Automatic pin.lnk', 'Manual pin.lnk', 'OrbitCord.lnk'].map(name => join(directory, name)).sort());
        for (const write of writes) {
            assert.equal(write.operation, 'update');
            assert.deepEqual(write.changes, { icon, iconIndex: 0, appUserModelId: appId });
        }
        assert.equal(links['OrbitCord.lnk'].args, '--user-option');
        assert.equal(links['OrbitCord.lnk'].description, 'My pin');
        assert.equal(links['OrbitCord.lnk'].cwd, 'C:\\Apps\\OrbitCord');
        await updateShortcutIcons(directory, executable, appId, icon, shell, true);
        assert.equal(writes.length, 4);
        assert.equal(links['nested/Start menu.lnk'].icon, icon);
        assert.equal(links['nested/Start menu.lnk'].appUserModelId, appId);
        await updateShortcutIcons(join(directory, 'missing'), executable, appId, icon, shell);
        assert.equal(writes.length, 4);
        assert.equal(links['Other app.lnk'].icon, undefined);
        assert.equal(links['Other install.lnk'].icon, undefined);
    } finally { await rm(directory, { recursive: true, force: true }); }
});

test('selected icon reaches Desktop, Start menu and taskbar shortcuts again on relaunch', async () => {
    const root = await mkdtemp(join(tmpdir(), 'orbitcord-shortcuts-'));
    const appData = join(root, 'appdata'), desktop = join(root, 'redirected-desktop');
    const programData = join(root, 'programdata'), publicDirectory = join(root, 'public');
    const userData = join(root, 'userdata');
    const executable = 'C:\\Apps\\OrbitCord\\OrbitCord.exe';
    const source = new URL('../src-tauri/icons/app/mint.png', import.meta.url);
    const digest = createHash('sha256').update(readFileSync(source)).digest('hex').slice(0, 16);
    const icon = join(userData, 'app-icons', `dib-v1-${digest}.ico`);
    const shortcuts = [
        join(desktop, 'OrbitCord.lnk'),
        join(appData, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'OrbitCord', 'OrbitCord.lnk'),
        join(appData, 'Microsoft', 'Internet Explorer', 'Quick Launch', 'User Pinned', 'TaskBar', 'OrbitCord.lnk'),
        join(appData, 'Microsoft', 'Internet Explorer', 'Quick Launch', 'User Pinned', 'ImplicitAppShortcuts', 'group', 'OrbitCord.lnk'),
        join(programData, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'OrbitCord.lnk'),
        join(publicDirectory, 'Desktop', 'OrbitCord.lnk'),
    ];
    const shell = {
        readShortcutLink: path => JSON.parse(readFileSync(path, 'utf8')),
        writeShortcutLink(path, operation, changes) {
            assert.equal(operation, 'update');
            writeFileSync(path, JSON.stringify({ ...this.readShortcutLink(path), ...changes }));
            return true;
        },
    };
    const calls = [];
    const window = { setAppDetails: details => calls.push(details), setIcon: path => calls.push(path),
        isDestroyed: () => false, isVisible: () => true, setSkipTaskbar: skip => calls.push({ skip }) };
    const options = { userData, appData, desktop, programData, publicDirectory, executable, shell, packaged: true,
        nativeImage: { createFromBuffer() { throw new Error('Expected cached ICO'); } },
        tray: { setImage: path => calls.push({ tray: path }) } };
    try {
        await mkdir(join(userData, 'app-icons'), { recursive: true });
        await writeFile(icon, readFileSync(new URL('../src-tauri/icons/icon.ico', import.meta.url)));
        for (const path of shortcuts) {
            await mkdir(join(path, '..'), { recursive: true });
            await writeFile(path, JSON.stringify({ target: executable, args: '--keep-this', icon: 'old.ico', iconIndex: 0 }));
        }
        await applyWindowsIcon(window, source, options);
        for (const path of shortcuts) {
            assert.equal(shell.readShortcutLink(path).icon, icon);
            assert.equal(shell.readShortcutLink(path).args, '--keep-this');
        }
        assert.deepEqual(calls, [{ appId: 'dev.lowcord.app', appIconPath: icon, appIconIndex: 0,
            relaunchCommand: `"${executable}"`, relaunchDisplayName: 'OrbitCord' }, icon, { tray: icon }, { skip: true }, icon, { skip: false }]);
        // An installer may replace the shortcut. Starting with the saved icon
        // must repair it again rather than relying on the previous session.
        shell.writeShortcutLink(shortcuts[0], 'update', { icon: 'installer-default.ico' });
        await applyWindowsIcon(window, source, options);
        assert.equal(shell.readShortcutLink(shortcuts[0]).icon, icon);
        calls.length = 0;
        window.isVisible = () => false;
        await applyWindowsIcon(window, source, options);
        assert.equal(calls.some(call => typeof call === 'object' && 'skip' in call), false);
    } finally { await rm(root, { recursive: true, force: true }); }
});
