const { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } = require('node:fs');
const { join, win32 } = require('node:path');
const { createHash } = require('node:crypto');
const nextTurn = () => new Promise(resolve => setImmediate(resolve));

function iconBitmap(image, size) {
    // Use Windows DIB frames at every size. Unlike PNG-compressed frames,
    // these are decoded by both LoadImage and the shell's icon extractors.
    const pixels = image.resize({ width: size, height: size, quality: 'best' }).toBitmap();
    const maskStride = Math.ceil(size / 32) * 4;
    const frame = Buffer.alloc(40 + size * size * 4 + maskStride * size);
    frame.writeUInt32LE(40, 0);
    frame.writeInt32LE(size, 4);
    frame.writeInt32LE(size * 2, 8); // XOR bitmap followed by the AND mask
    frame.writeUInt16LE(1, 12);
    frame.writeUInt16LE(32, 14);
    frame.writeUInt32LE(size * size * 4, 20);
    for (let y = 0; y < size; y++) {
        for (let x = 0; x < size; x++) {
            const source = (y * size + x) * 4;
            const destination = 40 + ((size - y - 1) * size + x) * 4;
            const alpha = pixels[source + 3];
            // Electron returns premultiplied BGRA; ICO stores straight BGRA.
            for (let channel = 0; channel < 3; channel++) {
                frame[destination + channel] = alpha ? Math.min(255, Math.round(pixels[source + channel] * 255 / alpha)) : 0;
            }
            frame[destination + 3] = alpha;
            if (!alpha) frame[40 + size * size * 4 + (size - y - 1) * maskStride + (x >> 3)] |= 0x80 >> (x & 7);
        }
    }
    return frame;
}

// Explorer cannot read PNGs or Electron's virtual app.asar paths as icon
// resources. Keep real ICO files in userData, including after app updates.
function windowsIconPath(source, userData, nativeImage) {
    const png = readFileSync(source);
    const digest = createHash('sha256').update(png).digest('hex').slice(0, 16);
    const directory = join(userData, 'app-icons');
    // Change the cache key when the encoding changes; never reuse the earlier
    // PNG-frame resources that Explorer may already have cached.
    const destination = join(directory, `dib-v1-${digest}.ico`);
    if (existsSync(destination)) return destination;
    const image = nativeImage.createFromBuffer(png);
    if (image.isEmpty()) throw new Error('Could not load app icon');
    const sizes = [16, 20, 24, 32, 40, 48, 64, 128, 256];
    const images = sizes.map(size => iconBitmap(image, size));
    const header = Buffer.alloc(6 + sizes.length * 16);
    header.writeUInt16LE(1, 2); // ICO, not CUR
    header.writeUInt16LE(sizes.length, 4);
    let offset = header.length;
    sizes.forEach((size, index) => {
        const entry = 6 + index * 16;
        header[entry] = header[entry + 1] = size === 256 ? 0 : size;
        header.writeUInt16LE(1, entry + 4);
        header.writeUInt16LE(32, entry + 6);
        header.writeUInt32LE(images[index].length, entry + 8);
        header.writeUInt32LE(offset, entry + 12);
        offset += images[index].length;
    });
    mkdirSync(directory, { recursive: true });
    writeFileSync(destination, Buffer.concat([header, ...images]));
    return destination;
}

async function updateShortcutIcons(directory, executable, appId, icon, shell, recursive = false) {
    let entries;
    try { entries = readdirSync(directory, { withFileTypes: true }); }
    catch (error) {
        if (error.code === 'ENOENT') return;
        throw error;
    }
    for (const entry of entries) {
        const shortcutPath = join(directory, entry.name);
        try {
            if (recursive && entry.isDirectory()) {
                await updateShortcutIcons(shortcutPath, executable, appId, icon, shell, true);
                continue;
            }
            if (!entry.isFile() || !entry.name.toLowerCase().endsWith('.lnk')) continue;
            await nextTurn();
            const shortcut = shell.readShortcutLink(shortcutPath);
            // Manually created shortcuts may have no app ID. Match the exact
            // executable, and leave shortcuts belonging to another app alone.
            if ((shortcut.appUserModelId && shortcut.appUserModelId !== appId
                    && !shortcut.appUserModelId.startsWith('Microsoft.AutoGenerated.'))
                || win32.normalize(shortcut.target).toLowerCase() !== win32.normalize(executable).toLowerCase()) continue;
            if (shortcut.icon === icon && shortcut.iconIndex === 0 && shortcut.appUserModelId === appId) continue;
            if (!shell.writeShortcutLink(shortcutPath, 'update', { icon, iconIndex: 0, appUserModelId: appId })) {
                throw new Error('Could not update app shortcut icon');
            }
        } catch (error) {
            console.error('[lowcord] Shortcut icon:', shortcutPath, error.message);
        }
    }
}

async function applyWindowsIcon(window, source, { userData, nativeImage, shell, appData, desktop, programData, publicDirectory, executable, packaged, tray }) {
    const icon = windowsIconPath(source, userData, nativeImage);
    window.setAppDetails({ appId: 'dev.lowcord.app', appIconPath: icon, appIconIndex: 0,
        ...(packaged ? { relaunchCommand: `"${executable}"`, relaunchDisplayName: 'OrbitCord' } : {}),
    });
    window.setIcon(icon);
    tray?.setImage(icon);
    await nextTurn();
    if (packaged) {
        // Windows may use the launch shortcut rather than the window icon.
        // Update both launchers and pins, preserving their launch arguments.
        const directories = [
            [join(appData, 'Microsoft', 'Internet Explorer', 'Quick Launch', 'User Pinned', 'TaskBar'), false],
            [join(appData, 'Microsoft', 'Internet Explorer', 'Quick Launch', 'User Pinned', 'ImplicitAppShortcuts'), true],
            [join(appData, 'Microsoft', 'Windows', 'Start Menu', 'Programs'), true],
            ...(desktop ? [[desktop, false]] : []),
            ...(programData ? [[join(programData, 'Microsoft', 'Windows', 'Start Menu', 'Programs'), true]] : []),
            ...(publicDirectory ? [[join(publicDirectory, 'Desktop'), false]] : []),
        ];
        for (const [directory, recursive] of directories) {
            try { await updateShortcutIcons(directory, executable, 'dev.lowcord.app', icon, shell, recursive); }
            catch (error) { console.error('[lowcord] Shortcut icon:', directory, error.message); }
        }
    }
    // WM_SETICON changes the title bar and Alt+Tab icon, but a grouped/pinned
    // taskbar button can retain its old image. Re-register only this window,
    // after shortcut updates have notified Explorer. Never hide the window or
    // restart Explorer, and don't create a taskbar button for a tray-only app.
    if (!window.isDestroyed() && window.isVisible()) {
        window.setSkipTaskbar(true);
        try {
            await nextTurn();
            if (!window.isDestroyed()) window.setIcon(icon);
        } finally {
            if (!window.isDestroyed()) window.setSkipTaskbar(false);
        }
    }
    return icon;
}

module.exports = { applyWindowsIcon, windowsIconPath, updateShortcutIcons };
